language: generic
os: linux
dist: bionic
services:
  - docker

script:
  - docker build -t client:test -f client/Dockerfile.dev client
  - docker run --rm -e CI=true client:test npm test
  - echo "$DOCKER_PSW" | docker login -u $DOCKER_USR --password-stdin
  - make prod push

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-east-2-918077598026
  bucket_path: multi-docker
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
